baseURL = 'https://tangyanbiao.com'
languageCode = 'zh-CN'
title = '莴莴莴笋'
theme = ["plausible-hugo", "paper"]  # Add this theme to your already existing other themes
paginate = 10

[params]
  # color style
  color = 'light'                 # linen, wheat, gray, light

  # header social icons
  twitter = '_ww_watson'     # twitter.com/YOUR_TWITTER_ID
  github = 'tyanbiao'       # github.com/YOUR_GITHUB_ID
  rss = true

  # home page profile
  avatar = 'https://tangyanbiao.com/avatar.jpeg'
  # avatar = 'tyanbiao@gmail.com'
  name = 'wwwatson'
  bio = 'Enjoy programing'

  # misc
  disableHLJS = true              # disable requesting highlight.js
  monoDarkIcon = true             # show monochrome dark mode icon
  comments = true
[params.giscus]
  repo = 'tyanbiao/blog_discuss'
  repoId = 'R_kgDOKS_9KA'
  category = 'Announcements'
  categoryId = 'DIC_kwDOKS_9KM4CZRiS'
  mapping = 'pathname'
  theme = 'noborder_light'
  lang = 'zh-CN'
[params.plausible]
  enable = true  # Whether to enable plausible tracking
  domain = "tangyanbiao.com"  # Plausible "domain" name/id in your dashboard
  gitstar = false
  proxy_netlify = true

[menu]
  [[menu.main]]
    identifier = "产品笔记"
    name = "产品笔记"
    url = "/tags/产品笔记/"
    weight = 9

  [[menu.main]]
    identifier = "weekly"
    name = "Weekly"
    url = "/tags/weekly/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 11



  # [[menu.main]]
  #   identifier = "projects"
  #   name = "Projects"
  #   url = "/projects/"
  #   weight = 11