baseURL = 'http://example.org/'
languageCode = 'zh-CN'
title = '莴莴莴笋'
theme = "paper"

[params]
  # color style
  color = 'light'                 # linen, wheat, gray, light

  # header social icons
  twitter = '_ww_watson'     # twitter.com/YOUR_TWITTER_ID
  github = 'tyanbiao'       # github.com/YOUR_GITHUB_ID

  # home page profile
  avatar = 'https://images-1252366546.cos.ap-guangzhou.myqcloud.com/notes/2022-9-11/avatar.jpg'
  # avatar = 'tyanbiao@gmail.com'
  name = 'wwwatson'
  bio = 'Enjoy programing'

  # misc
  disableHLJS = true              # disable requesting highlight.js
  monoDarkIcon = true             # show monochrome dark mode icon

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  # [[menu.main]]
  #   identifier = "projects"
  #   name = "Projects"
  #   url = "/projects/"
  #   weight = 11